<?php

namespace DrDoh\TicketBundle\Repository;

/**
 * BuyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyerRepository extends \Doctrine\ORM\EntityRepository
{
}
