<?php

namespace DrDoh\TicketBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function TicketsAfterNow(){
            $qb = $this->createQueryBuilder('t');
            $now = new \DateTime();
            $qb
                ->where('t.date < :now')
                ->setParameter('now', $now)
                ;
            
            return $qb->getQuery()->getResult();
    }
}
