dr_doh_ticket_billetterie:
    path:     /
    defaults: { _controller: DrDohTicketBundle:Booking:ticketForm }

dr_doh_ticket_billetterie_2:
    path:     /visiteur
    defaults: { _controller: DrDohTicketBundle:Booking:guestForm }

dr_doh_ticket_billetterie_stipe:
    path:     /payement
    defaults: { _controller: DrDohTicketBundle:Booking:stripeForm }

dr_doh_ticket_billetterie_stipe_charge:
    path:     /charge
    defaults: { _controller: DrDohTicketBundle:Booking:stripeCharge }
  
