dr_doh_ticket_billetterie:
    path:     /
    defaults: { _controller: DrDohTicketBundle:Booking:ticketForm }

dr_doh_ticket_billetterie_2:
    path:     /visiteur
    defaults: { _controller: DrDohTicketBundle:Booking:guestForm }

dr_doh_ticket_billetterie_stipe:
    path:     /payement
    defaults: { _controller: DrDohTicketBundle:Booking:stripeForm }

dr_doh_ticket_billetterie_stipe_checkout:
    path:     /checkout
    defaults: { _controller: DrDohTicketBundle:Booking:stripeCheckout }

dr_doh_ticket_billetterie_sending_ticket:
    path:     /sending/{orderId}
    defaults: { _controller: DrDohTicketBundle:Booking:sendingTicket }

dr_doh_ticket_billetterie_test:
    path:     /test
    defaults: { _controller: DrDohTicketBundle:Booking:test }
  
