parameters:
    ticketstatus_qteMax: 1000
    ticketstatus_yearMax: 2020

    pricecal_full: 16
    pricecal_child: 8
    pricecal_baby: 0
    pricecal_senior: 12
    pricecal_discount: 10
    pricecal_devise: '€'
    pricecal_childMaxAge: 12
    pricecal_childMinAge: 4
    pricecal_seniorMinAge: 60

    stripe_secret_key: 'sk_test_VwDCVvhFbm8X0lNDfgBII72L'
    stripe_publishable_key: 'pk_test_Fq9NCZF4ZYN0Uh48FV4we6g8'

# services:
#     dr_doh_services.tickets_status:
#         public: true
#         autowire: true
#         class: DrDoh\TicketBundle\Services\DrDohTicketStatus
#         arguments:
#             $qteMax: '%ticketstatus_qteMax%'
#             $yearMax: '%ticketstatus_yearMax%'

#     dr_doh_services.price_cal:
#         public: true
#         class: DrDoh\TicketBundle\Services\DrDohPriceCal
#         arguments:
#             $fullPrice: '%pricecal_full%'
#             $childPrice: '%pricecal_child%'
#             $babyPrice: '%pricecal_baby%'
#             $seniorPrice: '%pricecal_senior%'
#             $discountPrice: '%pricecal_discount%'
#             $devise: '%pricecal_devise%'
#             $childMaxAge: '%pricecal_childMaxAge%'
#             $childMinAge: '%pricecal_childMinAge%'
#             $seniorMinAge: '%pricecal_seniorMinAge%'

#     dr_doh_services.stripe:
#         public: true
#         class: DrDoh\TicketBundle\Services\DrDohStripe
#         arguments: 
#             $secretKey: '%stripe_secret_key%'
#             $publishableKey: '%stripe_publishable_key%'

#     dr_doh_services.sendTickets:
#         public: true
#         class: DrDoh\TicketBundle\Services\DrDohSendTickets
#         arguments:
#             - "@templating"
#             - "@mailer"
